# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#test

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: netconfwroclaw
  imageName: netconfapp
  # buildConfiguration: 'Release'  
  # imageName: 'estatemanagerweb:$(build.buildId)'

steps:
- script: docker build -f ./NetConfApp/Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  displayName: 'docker build'
  
- script: |    
    docker login -u $(dockerId) -p $(dockerPassword) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)  
  displayName: 'Sending Image to Azure Container Registry'


